services:
  - type: web
    name: portfolio-advisor-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secure-secret-key
      - key: DEBUG
        value: False
      - fromDatabase:
          name: portfolio-advisor-db
          property: connectionString

databases:
  - name: portfolio-advisor-db
    plan: free